matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js:
        - 'node'

    - language: rust
      rust:
        - stable
      before_install:
        - cd crate
        - rustup component add clippy rustfmt
      script:
        - cargo fmt --all -- --check && cargo clippy
