matrix:
  fast_finish: true
  include:
    - language: node_js
      node_js:
        - 'node'
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start

    - language: rust
      rust:
        - stable
      before_install:
        - cd crate
        - rustup component add clippy rustfmt
      script:
        - cargo fmt --all -- --check && cargo clippy
